language: java
jdk:
- openjdk14
sudo: true
services:
  - postgresql
before_script:
  - psql -c 'create database chat;' -U postgres
notifications:
  email:
    recipients:
    - sergeykinn@mail.ru
    on_success: never
    on_failure: always

